/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * REST API仕様
 * BackEndのREST API仕様です
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  MarkerYml
} from './model/components-Marker.yml'
import type {
  MakerCreateBody
} from './model'



  /**
 * Marker登録APIです
 * @summary Marker登録API
 */
export const makerCreate = <TData = AxiosResponse<MarkerYml>>(
    makerCreateBody: MakerCreateBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/marker/create`,
      makerCreateBody,options
    );
  }

/**
 * Marker取得API(ID指定)です
 * @summary Marker取得API(ID指定)
 */
export const makerById = <TData = AxiosResponse<MarkerYml>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/marker/${id}`,options
    );
  }

export type MakerCreateResult = AxiosResponse<MarkerYml>
export type MakerByIdResult = AxiosResponse<MarkerYml>
