/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * REST API仕様
 * BackEndのREST API仕様です
 * OpenAPI spec version: 1.0.0
 */

/**
 * Commentオブジェクト
 */
export interface CommentYml {
  /** ID */
  id?: number;
  /** コメント文字列 */
  comment?: string;
}
