openapi: 3.0.0
info:
  title: REST API仕様
  description: "BackEndのREST API仕様です"
  version: 1.0.0
servers:
  - url: http://127.0.0.1:3000/
paths:
  /marker/{id}:
    get:
      operationId: get_maker_by_id
      summary: IDを指定してMarkerを取得する
      parameters:
        - name: id
          in: path
          required: true
          example: 100
          schema:
            type: integer
      responses:
        "200":
          description: 成功した場合
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Marker"
components:
  # Reusable schemas (data models)
  schemas:
    Marker:
      $ref: "./components/Marker.yml"
