/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * REST API仕様
 * BackEndのREST API仕様です
 * OpenAPI spec version: 1.0.0
 */
import type { MarkerYml } from '../components-Marker.yml/markerYml';

export type Schema = MarkerYml;
